manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: tomori-k
      url-base: https://github.com/tomori-k
    - name: zettaface
      url-base: https://github.com/zettaface
  projects:
    - name: zmk
      remote: tomori-k
      revision: v2025.11.30
      import: app/west.yml
    - name: zmk-keyboards-cheakee
      remote: tomori-k
      revision: v2025.11.30
    - name: zmk-pmw3610-driver
      remote: tomori-k
      revision: v2025.11.30
    - name: zmk-behavior-soft-off-local
      remote: tomori-k
      revision: v2025.11.30
    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main
  self:
    path: config
